/**
 * Shape Utilities for Whiteboard Animation
 * Defines shape types, configurations, and helper functions
 */

export interface ShapeConfig {
  shape: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  radius?: number;
  radiusX?: number;
  radiusY?: number;
  radiuses?: number[];
  points?: number[];
  sides?: number;
  numPoints?: number;
  innerRadius?: number;
  outerRadius?: number;
  fill?: string | string[];
  fills?: string[];
  stroke?: string | string[];
  strokes?: string[];
  strokeWidth?: number;
  opacity?: number;
  rotation?: number;
  cornerRadius?: number;
  fillMode?: string;
  lineCap?: string;
  lineJoin?: string;
  pointerLength?: number;
  pointerWidth?: number;
  tension?: number;
  tailDirection?: string;
  text?: string;
  fontSize?: number;
  fontFamily?: string;
  textFill?: string;
  backgroundColor?: string;
  padding?: number;
  align?: string;
  verticalAlign?: string;
  iconType?: string;
  size?: number;
  markers?: number;
  decorativeType?: string;
  character?: string;
}

export interface ShapeLayer {
  id: string;
  type: string;
  name: string;
  zIndex: number;
  position: { x: number; y: number };
  scale: number;
  opacity: number;
  shape_config: ShapeConfig;
}

export interface ShapeCategory {
  label: string;
  shapes: string[];
}

// Shape Types - Comprehensive Shape Library
export const ShapeType: Record<string, string> = {
  // Basic Shapes
  RECTANGLE: 'rectangle',
  SQUARE: 'square',
  CIRCLE: 'circle',
  ELLIPSE: 'ellipse',
  LINE: 'line',
  ARROW: 'arrow',
  ARROW_DOUBLE: 'arrow_double',
  ARROW_CURVE: 'arrow_curve',
  TRIANGLE: 'triangle',
  POLYGON: 'polygon',
  CONNECTOR: 'connector',
  TEXT_BOX: 'text_box',
  
  // Advanced Shapes
  STAR: 'star',
  CLOUD: 'cloud',
  BUBBLE: 'bubble',
  THOUGHT_BUBBLE: 'thought_bubble',
  HIGHLIGHT: 'highlight',
  BANNER: 'banner',
  HEXAGON: 'hexagon',
  CIRCLE_CONCENTRIC: 'circle_concentric',
  TIMELINE: 'timeline',
  ORG_NODE: 'org_node',
  
  // Decorative & Pedagogical Shapes
  ICON: 'icon',
  FRAME_DOODLE: 'frame_doodle',
  FRAME_RECT_DOODLE: 'frame_rect_doodle',
  FRAME_CIRCLE_DOODLE: 'frame_circle_doodle',
  FRAME_CLOUD_DOODLE: 'frame_cloud_doodle',
  ARROW_DOODLE: 'arrow_doodle',
  LINE_WAVE_DOODLE: 'line_wave_doodle',
  STAR_SHOOTING: 'star_shooting',
  EXPLOSION_SHAPE: 'explosion_shape',
  CIRCLE_SKETCH: 'circle_sketch',
  TRIANGLE_DOODLE: 'triangle_doodle',
  RECTANGLE_DOODLE: 'rectangle_doodle',
  ARROW_CURVE_DOODLE: 'arrow_curve_doodle',
  HIGHLIGHT_DOODLE: 'highlight_doodle',
  BUBBLE_DOODLE: 'bubble_doodle',
  CLOUD_DOODLE: 'cloud_doodle',
  UNDERLINE_ANIMATED: 'underline_animated',
  DECORATIVE_SHAPE: 'decorative_shape',
  
  // Number Shapes (0-10)
  NUMBER_0: 'number_0',
  NUMBER_1: 'number_1',
  NUMBER_2: 'number_2',
  NUMBER_3: 'number_3',
  NUMBER_4: 'number_4',
  NUMBER_5: 'number_5',
  NUMBER_6: 'number_6',
  NUMBER_7: 'number_7',
  NUMBER_8: 'number_8',
  NUMBER_9: 'number_9',
  NUMBER_10: 'number_10',
  
  // Alphabet Shapes (A-Z)
  LETTER_A: 'letter_a',
  LETTER_B: 'letter_b',
  LETTER_C: 'letter_c',
  LETTER_D: 'letter_d',
  LETTER_E: 'letter_e',
  LETTER_F: 'letter_f',
  LETTER_G: 'letter_g',
  LETTER_H: 'letter_h',
  LETTER_I: 'letter_i',
  LETTER_J: 'letter_j',
  LETTER_K: 'letter_k',
  LETTER_L: 'letter_l',
  LETTER_M: 'letter_m',
  LETTER_N: 'letter_n',
  LETTER_O: 'letter_o',
  LETTER_P: 'letter_p',
  LETTER_Q: 'letter_q',
  LETTER_R: 'letter_r',
  LETTER_S: 'letter_s',
  LETTER_T: 'letter_t',
  LETTER_U: 'letter_u',
  LETTER_V: 'letter_v',
  LETTER_W: 'letter_w',
  LETTER_X: 'letter_x',
  LETTER_Y: 'letter_y',
  LETTER_Z: 'letter_z',
};

// Default shape configurations - Doodle style (stroke only, black/white)
export const DEFAULT_SHAPE_CONFIGS: Record<string, ShapeConfig> = {
  [ShapeType.RECTANGLE]: {
    shape: ShapeType.RECTANGLE,
    x: 400,
    y: 300,
    width: 200,
    height: 150,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    cornerRadius: 0,
    fillMode: 'stroke',
  },
  [ShapeType.CIRCLE]: {
    shape: ShapeType.CIRCLE,
    x: 400,
    y: 300,
    radius: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.ELLIPSE]: {
    shape: ShapeType.ELLIPSE,
    x: 400,
    y: 300,
    radiusX: 150,
    radiusY: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    fillMode: 'stroke',
  },
  [ShapeType.LINE]: {
    shape: ShapeType.LINE,
    points: [100, 100, 400, 100],
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    lineCap: 'round',
    lineJoin: 'round',
    fillMode: 'stroke',
  },
  [ShapeType.ARROW]: {
    shape: ShapeType.ARROW,
    points: [100, 100, 400, 100],
    stroke: '#000000',
    strokeWidth: 3,
    fill: '#000000',
    opacity: 1,
    pointerLength: 20,
    pointerWidth: 20,
    lineCap: 'round',
    lineJoin: 'round',
    fillMode: 'stroke',
  },
  [ShapeType.TRIANGLE]: {
    shape: ShapeType.TRIANGLE,
    x: 400,
    y: 300,
    sides: 3,
    radius: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    fillMode: 'stroke',
  },
  [ShapeType.POLYGON]: {
    shape: ShapeType.POLYGON,
    x: 400,
    y: 300,
    sides: 6,
    radius: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    fillMode: 'stroke',
  },
  [ShapeType.TEXT_BOX]: {
    shape: ShapeType.TEXT_BOX,
    x: 400,
    y: 300,
    width: 300,
    height: 100,
    text: 'Text Box',
    fontSize: 24,
    fontFamily: 'Arial',
    fill: '#000000',
    stroke: '#000000',
    strokeWidth: 3,
    backgroundColor: 'transparent',
    opacity: 1,
    padding: 10,
    align: 'center',
    verticalAlign: 'middle',
  },
  [ShapeType.SQUARE]: {
    shape: ShapeType.SQUARE,
    x: 400,
    y: 300,
    width: 150,
    height: 150,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    cornerRadius: 0,
    fillMode: 'stroke',
  },
  [ShapeType.ARROW_DOUBLE]: {
    shape: ShapeType.ARROW_DOUBLE,
    points: [100, 100, 400, 100],
    stroke: '#000000',
    strokeWidth: 3,
    fill: '#000000',
    opacity: 1,
    pointerLength: 20,
    pointerWidth: 20,
    lineCap: 'round',
    lineJoin: 'round',
    fillMode: 'stroke',
  },
  [ShapeType.ARROW_CURVE]: {
    shape: ShapeType.ARROW_CURVE,
    points: [100, 100, 200, 50, 300, 100, 400, 100],
    stroke: '#000000',
    strokeWidth: 3,
    fill: '#000000',
    opacity: 1,
    pointerLength: 20,
    pointerWidth: 20,
    tension: 0.5,
    fillMode: 'stroke',
  },
  [ShapeType.CONNECTOR]: {
    shape: ShapeType.CONNECTOR,
    points: [100, 100, 100, 200, 300, 200],
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    lineCap: 'round',
    lineJoin: 'round',
    fillMode: 'stroke',
  },
  [ShapeType.STAR]: {
    shape: ShapeType.STAR,
    x: 400,
    y: 300,
    numPoints: 5,
    innerRadius: 40,
    outerRadius: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    fillMode: 'stroke',
  },
  [ShapeType.CLOUD]: {
    shape: ShapeType.CLOUD,
    x: 400,
    y: 300,
    width: 200,
    height: 120,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.BUBBLE]: {
    shape: ShapeType.BUBBLE,
    x: 400,
    y: 300,
    width: 200,
    height: 120,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    cornerRadius: 10,
    tailDirection: 'bottom-left',
    fillMode: 'stroke',
  },
  [ShapeType.THOUGHT_BUBBLE]: {
    shape: ShapeType.THOUGHT_BUBBLE,
    x: 400,
    y: 300,
    width: 200,
    height: 120,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.HIGHLIGHT]: {
    shape: ShapeType.HIGHLIGHT,
    x: 400,
    y: 300,
    width: 200,
    height: 40,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    fillMode: 'stroke',
  },
  [ShapeType.BANNER]: {
    shape: ShapeType.BANNER,
    x: 400,
    y: 300,
    width: 300,
    height: 60,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    text: 'Banner',
    fontSize: 20,
    fontFamily: 'Arial',
    textFill: '#000000',
    fillMode: 'stroke',
  },
  [ShapeType.HEXAGON]: {
    shape: ShapeType.HEXAGON,
    x: 400,
    y: 300,
    sides: 6,
    radius: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    fillMode: 'stroke',
  },
  [ShapeType.CIRCLE_CONCENTRIC]: {
    shape: ShapeType.CIRCLE_CONCENTRIC,
    x: 400,
    y: 300,
    radiuses: [40, 70, 100],
    fills: ['transparent', 'transparent', 'transparent'],
    strokes: ['#000000', '#000000', '#000000'],
    strokeWidth: 3,
    opacity: 1,
  },
  [ShapeType.TIMELINE]: {
    shape: ShapeType.TIMELINE,
    x: 400,
    y: 300,
    width: 400,
    height: 100,
    stroke: '#000000',
    strokeWidth: 3,
    fill: 'transparent',
    opacity: 1,
    markers: 4,
    fillMode: 'stroke',
  },
  [ShapeType.ORG_NODE]: {
    shape: ShapeType.ORG_NODE,
    x: 400,
    y: 300,
    width: 150,
    height: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    cornerRadius: 8,
    text: 'Node',
    fontSize: 16,
    fontFamily: 'Arial',
    textFill: '#000000',
    fillMode: 'stroke',
  },
  [ShapeType.ICON]: {
    shape: ShapeType.ICON,
    x: 400,
    y: 300,
    iconType: 'lightbulb',
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.FRAME_DOODLE]: {
    shape: ShapeType.FRAME_DOODLE,
    x: 400,
    y: 300,
    width: 250,
    height: 180,
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.FRAME_RECT_DOODLE]: {
    shape: ShapeType.FRAME_RECT_DOODLE,
    x: 400,
    y: 300,
    width: 250,
    height: 180,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.FRAME_CIRCLE_DOODLE]: {
    shape: ShapeType.FRAME_CIRCLE_DOODLE,
    x: 400,
    y: 300,
    radius: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.FRAME_CLOUD_DOODLE]: {
    shape: ShapeType.FRAME_CLOUD_DOODLE,
    x: 400,
    y: 300,
    width: 200,
    height: 120,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.ARROW_DOODLE]: {
    shape: ShapeType.ARROW_DOODLE,
    points: [100, 100, 400, 100],
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.LINE_WAVE_DOODLE]: {
    shape: ShapeType.LINE_WAVE_DOODLE,
    points: [100, 100, 400, 100],
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.STAR_SHOOTING]: {
    shape: ShapeType.STAR_SHOOTING,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.EXPLOSION_SHAPE]: {
    shape: ShapeType.EXPLOSION_SHAPE,
    x: 400,
    y: 300,
    size: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.CIRCLE_SKETCH]: {
    shape: ShapeType.CIRCLE_SKETCH,
    x: 400,
    y: 300,
    radius: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.TRIANGLE_DOODLE]: {
    shape: ShapeType.TRIANGLE_DOODLE,
    x: 400,
    y: 300,
    radius: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.RECTANGLE_DOODLE]: {
    shape: ShapeType.RECTANGLE_DOODLE,
    x: 400,
    y: 300,
    width: 200,
    height: 150,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.ARROW_CURVE_DOODLE]: {
    shape: ShapeType.ARROW_CURVE_DOODLE,
    points: [100, 100, 200, 50, 300, 100, 400, 100],
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.HIGHLIGHT_DOODLE]: {
    shape: ShapeType.HIGHLIGHT_DOODLE,
    x: 400,
    y: 300,
    width: 200,
    height: 40,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.BUBBLE_DOODLE]: {
    shape: ShapeType.BUBBLE_DOODLE,
    x: 400,
    y: 300,
    width: 200,
    height: 120,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.CLOUD_DOODLE]: {
    shape: ShapeType.CLOUD_DOODLE,
    x: 400,
    y: 300,
    width: 200,
    height: 120,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
  },
  [ShapeType.UNDERLINE_ANIMATED]: {
    shape: ShapeType.UNDERLINE_ANIMATED,
    points: [100, 100, 400, 100],
    stroke: '#000000',
    strokeWidth: 4,
    opacity: 1,
    lineCap: 'round',
    fillMode: 'stroke',
  },
  [ShapeType.DECORATIVE_SHAPE]: {
    shape: ShapeType.DECORATIVE_SHAPE,
    x: 400,
    y: 300,
    decorativeType: 'heart',
    size: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    rotation: 0,
    fillMode: 'stroke',
  },
  // Number Shapes (0-10)
  [ShapeType.NUMBER_0]: {
    shape: ShapeType.NUMBER_0,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '0',
  },
  [ShapeType.NUMBER_1]: {
    shape: ShapeType.NUMBER_1,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '1',
  },
  [ShapeType.NUMBER_2]: {
    shape: ShapeType.NUMBER_2,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '2',
  },
  [ShapeType.NUMBER_3]: {
    shape: ShapeType.NUMBER_3,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '3',
  },
  [ShapeType.NUMBER_4]: {
    shape: ShapeType.NUMBER_4,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '4',
  },
  [ShapeType.NUMBER_5]: {
    shape: ShapeType.NUMBER_5,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '5',
  },
  [ShapeType.NUMBER_6]: {
    shape: ShapeType.NUMBER_6,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '6',
  },
  [ShapeType.NUMBER_7]: {
    shape: ShapeType.NUMBER_7,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '7',
  },
  [ShapeType.NUMBER_8]: {
    shape: ShapeType.NUMBER_8,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '8',
  },
  [ShapeType.NUMBER_9]: {
    shape: ShapeType.NUMBER_9,
    x: 400,
    y: 300,
    size: 80,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '9',
  },
  [ShapeType.NUMBER_10]: {
    shape: ShapeType.NUMBER_10,
    x: 400,
    y: 300,
    size: 100,
    fill: 'transparent',
    stroke: '#000000',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: '10',
  },
  // Alphabet Shapes (A-Z)
  [ShapeType.LETTER_A]: {
    shape: ShapeType.LETTER_A,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'A',
  },
  [ShapeType.LETTER_B]: {
    shape: ShapeType.LETTER_B,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'B',
  },
  [ShapeType.LETTER_C]: {
    shape: ShapeType.LETTER_C,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'C',
  },
  [ShapeType.LETTER_D]: {
    shape: ShapeType.LETTER_D,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'D',
  },
  [ShapeType.LETTER_E]: {
    shape: ShapeType.LETTER_E,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'E',
  },
  [ShapeType.LETTER_F]: {
    shape: ShapeType.LETTER_F,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'F',
  },
  [ShapeType.LETTER_G]: {
    shape: ShapeType.LETTER_G,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'G',
  },
  [ShapeType.LETTER_H]: {
    shape: ShapeType.LETTER_H,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'H',
  },
  [ShapeType.LETTER_I]: {
    shape: ShapeType.LETTER_I,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'I',
  },
  [ShapeType.LETTER_J]: {
    shape: ShapeType.LETTER_J,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'J',
  },
  [ShapeType.LETTER_K]: {
    shape: ShapeType.LETTER_K,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'K',
  },
  [ShapeType.LETTER_L]: {
    shape: ShapeType.LETTER_L,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'L',
  },
  [ShapeType.LETTER_M]: {
    shape: ShapeType.LETTER_M,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'M',
  },
  [ShapeType.LETTER_N]: {
    shape: ShapeType.LETTER_N,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'N',
  },
  [ShapeType.LETTER_O]: {
    shape: ShapeType.LETTER_O,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'O',
  },
  [ShapeType.LETTER_P]: {
    shape: ShapeType.LETTER_P,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'P',
  },
  [ShapeType.LETTER_Q]: {
    shape: ShapeType.LETTER_Q,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'Q',
  },
  [ShapeType.LETTER_R]: {
    shape: ShapeType.LETTER_R,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'R',
  },
  [ShapeType.LETTER_S]: {
    shape: ShapeType.LETTER_S,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'S',
  },
  [ShapeType.LETTER_T]: {
    shape: ShapeType.LETTER_T,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'T',
  },
  [ShapeType.LETTER_U]: {
    shape: ShapeType.LETTER_U,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'U',
  },
  [ShapeType.LETTER_V]: {
    shape: ShapeType.LETTER_V,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'V',
  },
  [ShapeType.LETTER_W]: {
    shape: ShapeType.LETTER_W,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'W',
  },
  [ShapeType.LETTER_X]: {
    shape: ShapeType.LETTER_X,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'X',
  },
  [ShapeType.LETTER_Y]: {
    shape: ShapeType.LETTER_Y,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'Y',
  },
  [ShapeType.LETTER_Z]: {
    shape: ShapeType.LETTER_Z,
    x: 400,
    y: 300,
    size: 80,
    fill: '#10B981',
    stroke: '#047857',
    strokeWidth: 3,
    opacity: 1,
    fillMode: 'stroke',
    character: 'Z',
  },
};

/**
 * Create a new shape layer
 * @param {string} shapeType - Type of shape from ShapeType
 * @param {object} customConfig - Custom configuration to override defaults
 * @returns {object} Shape layer object
 */
export function createShapeLayer(shapeType: string, customConfig: Partial<ShapeConfig> = {}): ShapeLayer {
  const defaultConfig = DEFAULT_SHAPE_CONFIGS[shapeType];
  
  if (!defaultConfig) {
    throw new Error(`Unknown shape type: ${shapeType}`);
  }

  return {
    id: `layer-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'shape',
    name: `${shapeType.charAt(0).toUpperCase() + shapeType.slice(1)} Shape`,
    zIndex: 100,
    position: { x: 0, y: 0 },
    scale: 1.0,
    opacity: 1.0,
    shape_config: {
      ...defaultConfig,
      ...customConfig,
    },
  };
}

/**
 * Get shape display name
 * @param {string} shapeType - Type of shape
 * @returns {string} Display name
 */
export function getShapeDisplayName(shapeType: string): string {
  const names = {
    [ShapeType.RECTANGLE]: 'Rectangle',
    [ShapeType.SQUARE]: 'Square',
    [ShapeType.CIRCLE]: 'Circle',
    [ShapeType.ELLIPSE]: 'Ellipse',
    [ShapeType.LINE]: 'Line',
    [ShapeType.ARROW]: 'Arrow',
    [ShapeType.ARROW_DOUBLE]: 'Double Arrow',
    [ShapeType.ARROW_CURVE]: 'Curved Arrow',
    [ShapeType.TRIANGLE]: 'Triangle',
    [ShapeType.POLYGON]: 'Polygon',
    [ShapeType.CONNECTOR]: 'Connector',
    [ShapeType.TEXT_BOX]: 'Text Box',
    [ShapeType.STAR]: 'Star',
    [ShapeType.CLOUD]: 'Cloud',
    [ShapeType.BUBBLE]: 'Speech Bubble',
    [ShapeType.THOUGHT_BUBBLE]: 'Thought Bubble',
    [ShapeType.HIGHLIGHT]: 'Highlight',
    [ShapeType.BANNER]: 'Banner',
    [ShapeType.HEXAGON]: 'Hexagon',
    [ShapeType.CIRCLE_CONCENTRIC]: 'Concentric Circles',
    [ShapeType.TIMELINE]: 'Timeline',
    [ShapeType.ORG_NODE]: 'Org Node',
    [ShapeType.ICON]: 'Icon',
    [ShapeType.FRAME_DOODLE]: 'Doodle Frame',
    [ShapeType.FRAME_RECT_DOODLE]: 'Rect Frame Doodle',
    [ShapeType.FRAME_CIRCLE_DOODLE]: 'Circle Frame Doodle',
    [ShapeType.FRAME_CLOUD_DOODLE]: 'Cloud Frame Doodle',
    [ShapeType.ARROW_DOODLE]: 'Arrow Doodle',
    [ShapeType.LINE_WAVE_DOODLE]: 'Wave Line Doodle',
    [ShapeType.STAR_SHOOTING]: 'Shooting Star',
    [ShapeType.EXPLOSION_SHAPE]: 'Explosion',
    [ShapeType.CIRCLE_SKETCH]: 'Circle Sketch',
    [ShapeType.TRIANGLE_DOODLE]: 'Triangle Doodle',
    [ShapeType.RECTANGLE_DOODLE]: 'Rectangle Doodle',
    [ShapeType.ARROW_CURVE_DOODLE]: 'Curve Arrow Doodle',
    [ShapeType.HIGHLIGHT_DOODLE]: 'Highlight Doodle',
    [ShapeType.BUBBLE_DOODLE]: 'Bubble Doodle',
    [ShapeType.CLOUD_DOODLE]: 'Cloud Doodle',
    [ShapeType.UNDERLINE_ANIMATED]: 'Underline',
    [ShapeType.DECORATIVE_SHAPE]: 'Decorative',
    // Numbers
    [ShapeType.NUMBER_0]: '0',
    [ShapeType.NUMBER_1]: '1',
    [ShapeType.NUMBER_2]: '2',
    [ShapeType.NUMBER_3]: '3',
    [ShapeType.NUMBER_4]: '4',
    [ShapeType.NUMBER_5]: '5',
    [ShapeType.NUMBER_6]: '6',
    [ShapeType.NUMBER_7]: '7',
    [ShapeType.NUMBER_8]: '8',
    [ShapeType.NUMBER_9]: '9',
    [ShapeType.NUMBER_10]: '10',
    // Letters
    [ShapeType.LETTER_A]: 'A',
    [ShapeType.LETTER_B]: 'B',
    [ShapeType.LETTER_C]: 'C',
    [ShapeType.LETTER_D]: 'D',
    [ShapeType.LETTER_E]: 'E',
    [ShapeType.LETTER_F]: 'F',
    [ShapeType.LETTER_G]: 'G',
    [ShapeType.LETTER_H]: 'H',
    [ShapeType.LETTER_I]: 'I',
    [ShapeType.LETTER_J]: 'J',
    [ShapeType.LETTER_K]: 'K',
    [ShapeType.LETTER_L]: 'L',
    [ShapeType.LETTER_M]: 'M',
    [ShapeType.LETTER_N]: 'N',
    [ShapeType.LETTER_O]: 'O',
    [ShapeType.LETTER_P]: 'P',
    [ShapeType.LETTER_Q]: 'Q',
    [ShapeType.LETTER_R]: 'R',
    [ShapeType.LETTER_S]: 'S',
    [ShapeType.LETTER_T]: 'T',
    [ShapeType.LETTER_U]: 'U',
    [ShapeType.LETTER_V]: 'V',
    [ShapeType.LETTER_W]: 'W',
    [ShapeType.LETTER_X]: 'X',
    [ShapeType.LETTER_Y]: 'Y',
    [ShapeType.LETTER_Z]: 'Z',
  };
  return names[shapeType] || shapeType;
}

/**
 * Get shape icon (emoji or symbol)
 * @param {string} shapeType - Type of shape
 * @returns {string} Icon
 */
export function getShapeIcon(shapeType: string): string {
  const icons = {
    [ShapeType.RECTANGLE]: '▭',
    [ShapeType.SQUARE]: '◻',
    [ShapeType.CIRCLE]: '●',
    [ShapeType.ELLIPSE]: '⬭',
    [ShapeType.LINE]: '─',
    [ShapeType.ARROW]: '→',
    [ShapeType.ARROW_DOUBLE]: '↔',
    [ShapeType.ARROW_CURVE]: '↪',
    [ShapeType.TRIANGLE]: '▲',
    [ShapeType.POLYGON]: '⬡',
    [ShapeType.CONNECTOR]: '⌞',
    [ShapeType.TEXT_BOX]: '📝',
    [ShapeType.STAR]: '★',
    [ShapeType.CLOUD]: '☁',
    [ShapeType.BUBBLE]: '💬',
    [ShapeType.THOUGHT_BUBBLE]: '💭',
    [ShapeType.HIGHLIGHT]: '🖍',
    [ShapeType.BANNER]: '🎗',
    [ShapeType.HEXAGON]: '⬡',
    [ShapeType.CIRCLE_CONCENTRIC]: '◎',
    [ShapeType.TIMELINE]: '📅',
    [ShapeType.ORG_NODE]: '🔲',
    [ShapeType.ICON]: '💡',
    [ShapeType.FRAME_DOODLE]: '✏',
    [ShapeType.FRAME_RECT_DOODLE]: '▢',
    [ShapeType.FRAME_CIRCLE_DOODLE]: '○',
    [ShapeType.FRAME_CLOUD_DOODLE]: '☁',
    [ShapeType.ARROW_DOODLE]: '➜',
    [ShapeType.LINE_WAVE_DOODLE]: '〰',
    [ShapeType.STAR_SHOOTING]: '⭐',
    [ShapeType.EXPLOSION_SHAPE]: '💥',
    [ShapeType.CIRCLE_SKETCH]: '◯',
    [ShapeType.TRIANGLE_DOODLE]: '△',
    [ShapeType.RECTANGLE_DOODLE]: '▯',
    [ShapeType.ARROW_CURVE_DOODLE]: '⤷',
    [ShapeType.HIGHLIGHT_DOODLE]: '✍',
    [ShapeType.BUBBLE_DOODLE]: '💬',
    [ShapeType.CLOUD_DOODLE]: '☁',
    [ShapeType.UNDERLINE_ANIMATED]: '＿',
    [ShapeType.DECORATIVE_SHAPE]: '♥',
    // Numbers
    [ShapeType.NUMBER_0]: '0️⃣',
    [ShapeType.NUMBER_1]: '1️⃣',
    [ShapeType.NUMBER_2]: '2️⃣',
    [ShapeType.NUMBER_3]: '3️⃣',
    [ShapeType.NUMBER_4]: '4️⃣',
    [ShapeType.NUMBER_5]: '5️⃣',
    [ShapeType.NUMBER_6]: '6️⃣',
    [ShapeType.NUMBER_7]: '7️⃣',
    [ShapeType.NUMBER_8]: '8️⃣',
    [ShapeType.NUMBER_9]: '9️⃣',
    [ShapeType.NUMBER_10]: '🔟',
    // Letters
    [ShapeType.LETTER_A]: '🅰',
    [ShapeType.LETTER_B]: '🅱',
    [ShapeType.LETTER_C]: 'C',
    [ShapeType.LETTER_D]: 'D',
    [ShapeType.LETTER_E]: 'E',
    [ShapeType.LETTER_F]: 'F',
    [ShapeType.LETTER_G]: 'G',
    [ShapeType.LETTER_H]: 'H',
    [ShapeType.LETTER_I]: 'I',
    [ShapeType.LETTER_J]: 'J',
    [ShapeType.LETTER_K]: 'K',
    [ShapeType.LETTER_L]: 'L',
    [ShapeType.LETTER_M]: 'M',
    [ShapeType.LETTER_N]: 'N',
    [ShapeType.LETTER_O]: 'O',
    [ShapeType.LETTER_P]: 'P',
    [ShapeType.LETTER_Q]: 'Q',
    [ShapeType.LETTER_R]: 'R',
    [ShapeType.LETTER_S]: 'S',
    [ShapeType.LETTER_T]: 'T',
    [ShapeType.LETTER_U]: 'U',
    [ShapeType.LETTER_V]: 'V',
    [ShapeType.LETTER_W]: 'W',
    [ShapeType.LETTER_X]: 'X',
    [ShapeType.LETTER_Y]: 'Y',
    [ShapeType.LETTER_Z]: 'Z',
  };
  return icons[shapeType] || '◇';
}

/**
 * Calculate polygon points
 * @param {number} sides - Number of sides
 * @param {number} radius - Radius
 * @returns {array} Array of points [x1, y1, x2, y2, ...]
 */
export function calculatePolygonPoints(sides: number, radius: number): number[] {
  const points: number[] = [];
  for (let i = 0; i < sides; i++) {
    const angle = (i * 2 * Math.PI) / sides - Math.PI / 2;
    const x = radius * Math.cos(angle);
    const y = radius * Math.sin(angle);
    points.push(x, y);
  }
  return points;
}

/**
 * Validate and sanitize shape configuration
 * @param {object} config - Shape configuration
 * @returns {object} Sanitized configuration
 */
export function sanitizeShapeConfig(config: ShapeConfig): ShapeConfig {
  const sanitized = { ...config };
  
  // Ensure numeric values are valid
  if (sanitized.strokeWidth !== undefined) {
    sanitized.strokeWidth = Math.max(0, Number(sanitized.strokeWidth) || 0);
  }
  
  if (sanitized.opacity !== undefined) {
    sanitized.opacity = Math.max(0, Math.min(1, Number(sanitized.opacity) || 1));
  }
  
  if (sanitized.rotation !== undefined) {
    sanitized.rotation = Number(sanitized.rotation) || 0;
  }
  
  // Ensure colors are valid
  if (sanitized.fill && typeof sanitized.fill === 'string' && !sanitized.fill.startsWith('#')) {
    sanitized.fill = '#' + sanitized.fill;
  }
  
  if (sanitized.stroke && typeof sanitized.stroke === 'string' && !sanitized.stroke.startsWith('#')) {
    sanitized.stroke = '#' + sanitized.stroke;
  }
  
  return sanitized;
}

/**
 * Get shape categories for UI organization
 * @returns {object} Categorized shapes
 */
export function getShapeCategories(): Record<string, ShapeCategory> {
  return {
    basic: {
      label: 'Basic Shapes',
      shapes: [
        ShapeType.RECTANGLE,
        ShapeType.SQUARE,
        ShapeType.CIRCLE,
        ShapeType.ELLIPSE,
        ShapeType.TRIANGLE,
        ShapeType.HEXAGON,
        ShapeType.POLYGON,
      ],
    },
    lines: {
      label: 'Lines & Arrows',
      shapes: [
        ShapeType.LINE,
        ShapeType.ARROW,
        ShapeType.ARROW_DOUBLE,
        ShapeType.ARROW_CURVE,
        ShapeType.CONNECTOR,
      ],
    },
    advanced: {
      label: 'Advanced',
      shapes: [
        ShapeType.STAR,
        ShapeType.CLOUD,
        ShapeType.BUBBLE,
        ShapeType.THOUGHT_BUBBLE,
        ShapeType.BANNER,
        ShapeType.CIRCLE_CONCENTRIC,
        ShapeType.TIMELINE,
        ShapeType.ORG_NODE,
      ],
    },
    doodle: {
      label: 'Doodle',
      shapes: [
        ShapeType.FRAME_DOODLE,
        ShapeType.FRAME_RECT_DOODLE,
        ShapeType.FRAME_CIRCLE_DOODLE,
        ShapeType.FRAME_CLOUD_DOODLE,
        ShapeType.ARROW_DOODLE,
        ShapeType.LINE_WAVE_DOODLE,
        ShapeType.STAR_SHOOTING,
        ShapeType.EXPLOSION_SHAPE,
        ShapeType.CIRCLE_SKETCH,
        ShapeType.TRIANGLE_DOODLE,
        ShapeType.RECTANGLE_DOODLE,
        ShapeType.ARROW_CURVE_DOODLE,
        ShapeType.HIGHLIGHT_DOODLE,
        ShapeType.BUBBLE_DOODLE,
        ShapeType.CLOUD_DOODLE,
      ],
    },
    decorative: {
      label: 'Decorative',
      shapes: [
        ShapeType.HIGHLIGHT,
        ShapeType.ICON,
        ShapeType.UNDERLINE_ANIMATED,
        ShapeType.DECORATIVE_SHAPE,
      ],
    },
    numbers: {
      label: 'Numbers',
      shapes: [
        ShapeType.NUMBER_0,
        ShapeType.NUMBER_1,
        ShapeType.NUMBER_2,
        ShapeType.NUMBER_3,
        ShapeType.NUMBER_4,
        ShapeType.NUMBER_5,
        ShapeType.NUMBER_6,
        ShapeType.NUMBER_7,
        ShapeType.NUMBER_8,
        ShapeType.NUMBER_9,
        ShapeType.NUMBER_10,
      ],
    },
    letters: {
      label: 'Letters',
      shapes: [
        ShapeType.LETTER_A,
        ShapeType.LETTER_B,
        ShapeType.LETTER_C,
        ShapeType.LETTER_D,
        ShapeType.LETTER_E,
        ShapeType.LETTER_F,
        ShapeType.LETTER_G,
        ShapeType.LETTER_H,
        ShapeType.LETTER_I,
        ShapeType.LETTER_J,
        ShapeType.LETTER_K,
        ShapeType.LETTER_L,
        ShapeType.LETTER_M,
        ShapeType.LETTER_N,
        ShapeType.LETTER_O,
        ShapeType.LETTER_P,
        ShapeType.LETTER_Q,
        ShapeType.LETTER_R,
        ShapeType.LETTER_S,
        ShapeType.LETTER_T,
        ShapeType.LETTER_U,
        ShapeType.LETTER_V,
        ShapeType.LETTER_W,
        ShapeType.LETTER_X,
        ShapeType.LETTER_Y,
        ShapeType.LETTER_Z,
      ],
    },
    text: {
      label: 'Text',
      shapes: [
        ShapeType.TEXT_BOX,
      ],
    },
  };
}

export default {
  ShapeType,
  DEFAULT_SHAPE_CONFIGS,
  createShapeLayer,
  getShapeDisplayName,
  getShapeIcon,
  calculatePolygonPoints,
  sanitizeShapeConfig,
  getShapeCategories,
};
